/**
 * Turns whatever the salon uploads into crisp, retina/4K-ready photography.
 *
 *   npm run photos      (also runs automatically as part of `npm run build`)
 *
 * For every image in `public/images/` it writes a ladder of widths as both
 * AVIF/WebP (small) and JPEG (universal) into `public/images/opt/`, plus a
 * TypeScript manifest so <SmartImage> can emit a proper `srcset`. The browser
 * then downloads the sharpest size that the screen actually needs — a 4K
 * display gets the 3200px file, a phone gets 480px.
 *
 * Note on "converting to 4K": pixels that were never captured cannot be
 * invented. We never upscale past the original (that only adds blur); instead
 * we keep the full captured detail, apply a light unsharp mask, and serve it at
 * device-pixel-ratio 2–3 so it looks razor sharp on 4K screens.
 */
import { mkdir, readdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const IMAGES = path.resolve('public/images');
const OUT = path.join(IMAGES, 'opt');
const MANIFEST = path.resolve('src/data/photoManifest.ts');

const WIDTHS = [480, 768, 1200, 1600, 2400, 3200];
const EXT = /\.(jpe?g|png|webp|avif)$/i;

/** Recursively collect source images, skipping our own output folder. */
async function collect(dir, base = '') {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (entry.name === 'opt') continue;
    const rel = path.join(base, entry.name);
    if (entry.isDirectory()) out.push(...(await collect(path.join(dir, entry.name), rel)));
    else if (EXT.test(entry.name)) out.push(rel);
  }
  return out;
}

const slug = (rel) => rel.replace(EXT, '').replace(/[\\/\s]+/g, '-').toLowerCase();

const sources = await collect(IMAGES);
if (sources.length === 0) {
  console.log('· no photos in public/images yet — writing an empty manifest');
}

await mkdir(OUT, { recursive: true });

const manifest = {};

for (const rel of sources) {
  const abs = path.join(IMAGES, rel);
  const name = slug(rel);

  try {
    const input = sharp(abs, { failOn: 'none' }).rotate(); // honour EXIF orientation
    const meta = await input.metadata();
    const sourceWidth = meta.width ?? 0;
    if (!sourceWidth) {
      console.warn('✗ unreadable', rel);
      continue;
    }

    const widths = WIDTHS.filter((w) => w <= sourceWidth);
    if (widths.length === 0) widths.push(sourceWidth); // very small source
    if (!widths.includes(sourceWidth) && sourceWidth < WIDTHS[WIDTHS.length - 1]) {
      widths.push(sourceWidth); // keep every captured pixel as the top tier
    }

    const written = [];
    for (const width of widths) {
      const base = `${name}-${width}`;
      const pipeline = sharp(abs, { failOn: 'none' })
        .rotate()
        .resize({ width, withoutEnlargement: true, fit: 'inside', kernel: 'lanczos3' })
        // light unsharp mask: recovers the crispness lost when downscaling
        .sharpen({ sigma: 0.7, m1: 0.4, m2: 0.9 });

      await pipeline
        .clone()
        .webp({ quality: 82, effort: 5, smartSubsample: true })
        .toFile(path.join(OUT, `${base}.webp`));

      await pipeline
        .clone()
        .jpeg({ quality: 84, progressive: true, mozjpeg: true, chromaSubsampling: '4:4:4' })
        .toFile(path.join(OUT, `${base}.jpg`));

      written.push(width);
    }

    manifest[`images/${rel.split(path.sep).join('/')}`] = {
      base: `images/opt/${name}`,
      widths: written,
      width: sourceWidth,
      height: meta.height ?? 0,
    };

    const { size } = await stat(abs);
    console.log(
      `✓ ${rel} — ${sourceWidth}px source → ${written.join('/')} (${Math.round(size / 1024)} KB in)`,
    );
  } catch (err) {
    console.warn('✗ failed', rel, err.message);
  }
}

await writeFile(
  MANIFEST,
  `/* AUTO-GENERATED by scripts/process-photos.mjs — do not edit by hand. */

export type PhotoVariants = {
  /** Path prefix, e.g. \`images/opt/hair\`. Append \`-<width>.webp|jpg\`. */
  base: string;
  widths: number[];
  width: number;
  height: number;
};

export const photoManifest: Record<string, PhotoVariants> = ${JSON.stringify(
    manifest,
    null,
    2,
  )} as const;
`,
  'utf8',
);

console.log(`\n✓ manifest written with ${Object.keys(manifest).length} photo(s)`);
