/* AUTO-GENERATED by scripts/process-photos.mjs — do not edit by hand. */

export type PhotoVariants = {
  /** Path prefix, e.g. `images/opt/hair`. Append `-<width>.webp|jpg`. */
  base: string;
  widths: number[];
  width: number;
  height: number;
};

export const photoManifest: Record<string, PhotoVariants> = {
  "images/stock/barber.jpg": {
    "base": "images/opt/stock-barber",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 640
  },
  "images/stock/bridal-2.jpg": {
    "base": "images/opt/stock-bridal-2",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1440
  },
  "images/stock/bridal.jpg": {
    "base": "images/opt/stock-bridal",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 1440
  },
  "images/stock/facial.jpg": {
    "base": "images/opt/stock-facial",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 640
  },
  "images/stock/interior-wide.jpg": {
    "base": "images/opt/stock-interior-wide",
    "widths": [
      480,
      768,
      1200,
      1600,
      1920
    ],
    "width": 1920,
    "height": 1282
  },
  "images/stock/nails-2.jpg": {
    "base": "images/opt/stock-nails-2",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 641
  },
  "images/stock/nails.jpg": {
    "base": "images/opt/stock-nails",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 640
  },
  "images/stock/skin.jpg": {
    "base": "images/opt/stock-skin",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 640
  },
  "images/stock/spa.jpg": {
    "base": "images/opt/stock-spa",
    "widths": [
      480,
      768,
      960
    ],
    "width": 960,
    "height": 640
  }
} as const;
